#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH -p fast.q
#SBATCH --mem-per-cpu=1G
#SBATCH --time=0-00:15:00     # 0days, 0hours, 15 minutes
#SBATCH --output=monte_carlo_pi_%j.stdout
#SBATCH --job-name=monte_carlo_pi_job
#SBATCH --export=ALL

module load anaconda3
echo "Slurm gave us $SLURM_CPUS_ON_NODE CPU(S) on this node."
python python_par_example.py $SLURM_CPUS_ON_NODE
